### PR TITLE
Fix secret type count passed to key-value reader

### LINKED ISSUE #299: BUG: miss handle secret type in S3 key-value reader
Hi team, I think for S3 filesystem we have 4 types of secrets, but somehow we only pass 3 of them into the key-value reader.
https://github.com/duckdb/duckdb-httpfs/blob/de34f7b1f342071518d3903c556c846b48719487/src/s3fs.cpp#L199-L200

### PR DESCRIPTION
**Pull request by dentiny**
Fixes https://github.com/duckdb/duckdb-httpfs/issues/299

I wish we could pass by `std::span`: https://en.cppreference.com/w/cpp/container/span.html

### CODE REVIEW

File: src/s3fs.cpp [hunk 1]
```diff
@@ -197,7 +197,7 @@ S3AuthParams S3AuthParams::ReadFrom(optional_ptr<FileOpener> opener, FileOpenerI
 	}
 
 	const char *secret_types[] = {"s3", "r2", "gcs", "aws"};
-	S3KeyValueReader secret_reader(*opener, info, secret_types, 3);
+	S3KeyValueReader secret_reader(*opener, info, secret_types, sizeof(secret_types) / sizeof(secret_types[0]));
```
Comment (carlopi) [inline src/s3fs.cpp]:
```suggestion
	S3KeyValueReader secret_reader(*opener, info, secret_types, 4));
```

I think `S3KeyValueReader` needs a rework, ideally it should not be that low level to take const char ** + id.

I would say either fixing the bug in the simple way, or restructuring the `KeyValueReaders` interface, but I think simplest is just include `aws` as well.

**Review by carlopi — CHANGES_REQUESTED** [review]
Thanks for finding this, I would keep it simpler and just put 4 for correctness, and move the refactor to later.

File: src/s3fs.cpp (hunk 1 above)
Comment (dentiny) [reply src/s3fs.cpp]: sure, if we decided to refactor I will use a plain 4 then -- updated!

**Review by carlopi — APPROVED** [review]

**Comment by carlopi** [comment]
Thanks!
